export const CABINETS = [
    { id: 'track', number: '01', name: 'Track Attack', category: 'ACTION', color: '#eaa35b', tag: 'Collect. Bank. Escape.', description: 'Recover your records before the algorithm gets them.', controls: 'WASD / arrows to move · Space to dash · P to pause', instructions: ['Collect scattered records and return to the center archive to bank them. You can carry four; a full crate slows you down.', 'The red Skip chases you, the blue Algorithm predicts your path, and the Aux Thief patrols valuable records. Getting tagged drops unbanked records.', 'Dash with Space to escape. Shields absorb one tag. Bank the complete collection to advance through four listening eras.'], load: () => import('../games/trackAttack/trackAttack.js') },
    { id: 'world', number: '02', name: 'World Tour', category: 'EXPLORATION', color: '#7bc0b0', tag: 'Your music. No borders.', description: 'Put your listening on the map. Collect a passport of origins.', controls: 'Drag to rotate · Scroll or +/− to zoom · Click a marker', instructions: ['Rotate the 3D globe and visit the origins of your artists. Every new artist stamps your music passport.', 'Complete the tour by discovering six locations. Birthplaces and band formation locations are distinguished.', 'Live origins come from Wikidata. Ambiguous identities and missing locations stay unknown; the demo includes an offline reference set.'], load: () => import('../games/worldTour/worldTour.js') },
    { id: 'roast', number: '03', name: 'Roast Machine', category: 'COMEDY', color: '#d98573', tag: 'Taste under investigation.', description: 'One listening profile. A suspiciously long receipt.', controls: 'Click to print · Choose your favorite charge', instructions: ['The machine examines your listening profile and prints a selection of handcrafted roasts.', 'Every charge points to the data that triggered it. Pick your most accurate charge and collect the report.', 'All processing happens in your browser. These playful ratings are fictional, not a judgment about you.'], load: () => import('../games/roastMachine/roastMachine.js') },
    { id: 'higher', number: '04', name: 'Who’s Higher?', category: 'TRIVIA', color: '#c2c887', tag: 'Know your own rotation?', description: 'Two favorites. Ten rounds. Only one ranks higher.', controls: 'Click a choice · 1 / 2 to choose · Enter for next round', instructions: ['Choose the artist or track ranked higher in your listening profile. A smaller rank number wins.', 'Ten rounds move from easy gaps to near neighbors. Build a streak for a bigger score.', 'Switch time ranges or compare ranking movement. In movement mode, the larger climb from long-term to recent wins.'], load: () => import('../games/whosHigher/whosHigher.js') },
    { id: 'aux', number: '05', name: 'The Aux Cord', category: 'STRATEGY', color: '#b5a1cd', tag: 'Read the room.', description: 'One aux cord. A crowd with very particular opinions.', controls: 'Choose a record · Read reactions · Deduce preferences', instructions: ['Keep the party alive for twelve selections. Each guest has a hidden rule tied to your music data.', 'Read reactions, compare releases, ranks, albums, and saved tracks. New guests arrive as the party grows.', 'You get two hand refreshes. Repeats bore the room. Use the guest notebook to identify preferences and earn an energy boost.'], load: () => import('../games/auxCord/auxCord.js') },
    { id: 'drop', number: '06', name: 'Album Drop', category: 'FALLING RECORDS', color: '#94a9d5', tag: 'Make room for one more.', description: 'Stack records. Connect artists. Set off a chain reaction.', controls: '← / → move · ↑ swap · ↓ soft drop · Space hard drop', instructions: ['Drop two records into the crate. Move them left or right and swap their order before they land.', 'Three or more connected records by the same artist clear, with extra points for matching albums and eras. Gravity can trigger cascades.', 'Top-five tracks clear with just two matching records. Survive forty drops without overflowing.'], load: () => import('../games/albumDrop/albumDrop.js') },
    { id: 'crate', number: '07', name: 'Crate Code', category: 'DEDUCTION', color: '#d4bf83', tag: 'Every record leaves a clue.', description: 'Four missing records. Twelve suspects. Crack the collection.', controls: 'Select a slot, then a record · Check the crate · Scan for a clue', instructions: ['Reconstruct four missing records from clues about artist ranks, release eras, albums, and track rankings.', 'Select a slot and assign a candidate. Each check tells you how many records are in the correct slots. You get five attempts.', 'Two scans reveal additional evidence at a score cost. Every generated puzzle has a unique solution.'], load: () => import('../games/crateCode/crateCode.js') },
];
