export const ACHIEVEMENTS = [
    { id: 'first-play', name: 'INSERT COIN', description: 'Finish your first cabinet.', coins: 25, tickets: 1 },
    { id: 'all-seven', name: 'CABINET COLLECTOR', description: 'Complete all seven cabinets.', coins: 150, tickets: 10 },
    { id: 'perfect-ear', name: 'PERFECT EAR', description: 'Win all ten Who’s Higher rounds.', coins: 100, tickets: 5 },
    { id: 'deep-cut', name: 'DEEP CUT', description: 'Win a close matchup below rank ten.', coins: 40, tickets: 2 },
    { id: 'worldwide', name: 'WORLDWIDE', description: 'Discover artists across five continents.', coins: 100, tickets: 6 },
    { id: 'first-stamp', name: 'FIRST STAMP', description: 'Discover your first artist location.', coins: 20, tickets: 1 },
    { id: 'full-clear', name: 'FULL CLEAR', description: 'Bank every record in a Track Attack level.', coins: 60, tickets: 3 },
    { id: 'unskippable', name: 'UNSKIPPABLE', description: 'Clear all four Track Attack levels.', coins: 120, tickets: 6 },
    { id: 'aux-survivor', name: 'AUX SURVIVOR', description: 'Complete twelve party selections with energy above 40.', coins: 80, tickets: 4 },
    { id: 'crowd-reader', name: 'CROWD READER', description: 'Correctly identify three guests’ hidden preferences.', coins: 60, tickets: 3 },
    { id: 'album-clear', name: 'ALBUM CLEAR', description: 'Clear a cluster from a single album.', coins: 30, tickets: 2 },
    { id: 'chain-reaction', name: 'CHAIN REACTION', description: 'Trigger a cascade in Album Drop.', coins: 50, tickets: 3 },
    { id: 'codebreaker', name: 'CODEBREAKER', description: 'Solve a Crate Code.', coins: 60, tickets: 3 },
    { id: 'clean-solve', name: 'CLEAN SOLVE', description: 'Solve a Crate Code on the first attempt without scanning.', coins: 100, tickets: 5 },
    { id: 'roasted', name: 'WELL DONE', description: 'Collect your first roast receipt.', coins: 20, tickets: 1 },
    { id: 'obsession', name: 'OBSESSION', description: 'Spot an artist rising ten or more places.', coins: 40, tickets: 2 },
    { id: 'archivist', name: 'ARCHIVIST', description: 'Interact with music from five decades.', coins: 70, tickets: 4 },
];
